### ISSUE TITLE
Look back through comp-data-sci for papers we recommended

### ISSUE THREAD

**Issue by CatalinaMedina** [mdogucu/group-meetings#1]
Add those recommendations to the reading-ideas.md

**Comment by CatalinaMedina** [comment]
I remember during one of our meetings Mine suggested we add a "must_read" column to note papers we thought everyone should read. Looking through the history of each of our "all_docs" files in "data\05-in-depth-analysis\01-initial-independent-reviews", only Mine and I had this column. @federicazoe, @hbendekgey, and @sinemdemirci if you remember having this column then let me know, because it must've been at a different step (aka a different file) or maybe was in private version never pushed. Unassign yourself if you don't think you ever noted these.

@mdogucu under your must_read column you had 5 marked "TRUE" and one marked "will read later". Looking at these articles I'm not positive if you wanted all of these to be added to the reading-ideas.md file in this repo (e.g. [Demchenko_2020_edison_data](https://ieeexplore.ieee.org/document/9041712) ). Can you please look at these five and let me know if you'd like them added to the reading ideas file?

- Brooks_2021_towards_culturally (doi 10.1007/s40593-021-00262-2)
- Demchenko_2020_edison_data (doi 10.1109/escience.2019.00076)
- Oliver_2021_undergraduate_data (doi 10.7717/peerj-cs.441)
- Sinha_2021_robust_effects (doi 10.1016/j.learninstruc.2021.101488)
- Wiktorski_2017_quantitative (doi 10.1109/cloudcom.2016.0109)
- Bornschlegl_2016_ivisbigdata (doi 10.1007/978-3-319-50070-6_1) marked "will read later"

**Comment by mdogucu** [comment]
Only the `must_read == TRUE` are relevant. "will read later" was a note to myself. Thanks!

**Comment by federicazoe** [comment]
I do not remember every using that column but I had taken note on my Zotero of papers to possibly read together.
I have just added those to the reading list and so I am de-assigning myself from this issue.

**Comment by CatalinaMedina** [comment]
We have resolved all of Mine's must reads and they have been added to the reading ideas file
